// <auto-generated />
namespace PrestigeWorldwide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class starthere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(starthere));
        
        string IMigrationMetadata.Id
        {
            get { return "201705010553025_starthere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
